### ISSUE TITLE
Documented location of Wealthsimple application credentials

### ISSUE THREAD

**Issue by mikaalnaik** [ahmedsakr/wstrade-api#66]
As a user of `wstrade-api` it's important for people to know how to obtain the `client_id` and other necessary credentials for user of this package.

Solutions:

Link to Wealthsimple page where application can sign up, or contact info to gain access. Would love to create a PR for this if you point me in the right direction.

**Comment by ahmedsakr** [comment]
Hi Mikaal, Thanks for the concern. Can you elaborate? Do you mean the login credentials (i.e., email and password)?

**Comment by mikaalnaik** [comment]
Hey @ahmedsakr,

My apologies. I actually got turned around and ended up creating an issue on the wrong repo. My apologies. I'd love to contribute sometime and help the migration to `v.1` if you create some issues sometime.


Sorry again for the wasted irrelevant issue!!!!

**Comment by ahmedsakr** [comment]
No worries. `v1.0.0` is already released and stable since last week, so everything is migrated!

If you wish to contribute, please read this document here first to ramp up: https://github.com/ahmedsakr/wstrade-api/blob/main/Contributing.md

The issues section is kinda dry now because v1 was just merged in last week. I'll be coming up with a lot more issues soon, some of which will be tagged "Good first issue" for new contributors.
